#ifndef __TASKS_PARAMITERS_H__
#define __TASKS_PARAMITERS_H__

#include "FreeRTOS.h"

#define TASK_DISPLAY_OLED_STACK_SIZE   (configMINIMAL_STACK_SIZE * 5)
#define TASK_DISPLAY_OLED_PRIORITY     (tskIDLE_PRIORITY + 1)

#define TASK_DRONE_CONTROL_STACK_SIZE  (configMINIMAL_STACK_SIZE * 3)
#define TASK_DRONE_CONTROL_PRIORITY    (tskIDLE_PRIORITY +1)

#define TASK_HTTP_SERVER_STACK_SIZE    (configMINIMAL_STACK_SIZE * 2)
#define TASK_HTTP_SERVER_PRIORITY      (tskIDLE_PRIORITY + 1)

#define TASK_TINYML_STACK_SIZE         (configMINIMAL_STACK_SIZE * 3)
#define TASK_TINYML_PRIORITY           (tskIDLE_PRIORITY + 1)

#define TASK_ADC_DMA_STACK_SIZE        (configMINIMAL_STACK_SIZE * 3)
#define TASK_ADC_DMA_PRIORITY          (tskIDLE_PRIORITY + 1)

#endif