#ifndef __TASKS_PARAMITERS_H__
#define __TASKS_PARAMITERS_H__

#include "FreeRTOS.h"
#include "task.h"

#define TASK_DISPLAY_OLED_STACK_SIZE   (configMINIMAL_STACK_SIZE * 3)
#define TASK_DISPLAY_OLED_PRIORITY     (tskIDLE_PRIORITY + 1)
#define TASK_DISPLAY_OLED_DELAY        (pdMS_TO_TICKS(500))

#define TASK_VU_LEDS_STACK_SIZE        (configMINIMAL_STACK_SIZE * 3)
#define TASK_VU_LEDS_PRIORITY          (tskIDLE_PRIORITY + 2)
#define TASK_VU_LEDS_DELAY             (pdMS_TO_TICKS(300))

#define TASK_DRONE_CONTROL_STACK_SIZE  (configMINIMAL_STACK_SIZE * 3)
#define TASK_DRONE_CONTROL_PRIORITY    (tskIDLE_PRIORITY + 3)
#define TASK_DRONE_CONTROL_DELAY       (pdMS_TO_TICKS(500))

#define TASK_HTTP_SERVER_STACK_SIZE    (configMINIMAL_STACK_SIZE * 3)
#define TASK_HTTP_SERVER_PRIORITY      (tskIDLE_PRIORITY + 2)
#define TASK_HTTP_SERVER_DELAY         (pdMS_TO_TICKS(500))

#define TASK_TINYML_STACK_SIZE         (configMINIMAL_STACK_SIZE * 8)
#define TASK_TINYML_PRIORITY           (tskIDLE_PRIORITY + 4)
#define TASK_TINYML_DELAY              (pdMS_TO_TICKS(200))

#define TASK_ADC_DMA_STACK_SIZE        (configMINIMAL_STACK_SIZE * 8)
#define TASK_ADC_DMA_PRIORITY          (tskIDLE_PRIORITY + 4)
#define TASK_ADC_DMA_DELAY             (pdMS_TO_TICKS(200))

#endif